### ISSUE TITLE
Question on `tf2` to transform between `base_link` and `camera`.

### ISSUE THREAD

**Issue by wangzizhe** [Tinker-Twins/Autonomy-Science-And-Systems#2]
Hi, 

I have a question on `tf2` to transform between `base_link` and `camera`.

For example, like this file here:
`Capstone Project/capstone_project/capstone_project/launch/apriltag_tracking_real.launch.py`

My question is how to get the values for the arguments. e.g. if I use a TurtleBot3 Waffle Pi. How can I get the right values?
```
        Node(
            package='tf2_ros',
            executable='static_transform_publisher',
            name='base_link_to_camera_tf',
            arguments = ['0.055', '0.000', '0.100',
                         '0.000', '1.571', '0.000',
                         'base_link', 'camera']
```

Thanks a lot in advance!

**Comment by Tinker-Twins** [comment]
You can use [this](https://github.com/Tinker-Twins/Autonomy-Science-And-Systems/blob/main/Capstone%20Project/capstone_project/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf) file directly if you are working with TurtleBot3 Waffle Pi.

The general idea is to physically measure the 6D relative pose transform (position + orientation) between the robot's `camera frame` (where the camera mudule is mounted) and `base frame` (center of the axle connecting the two driven wheels) as mentioned [here](https://github.com/Tinker-Twins/Autonomy-Science-And-Systems/tree/main/Capstone%20Project#robot-setup), and then enter these values in the launch file using the following format (in SI units):

![base_link_to_camera_tf](https://github.com/Tinker-Twins/Autonomy-Science-And-Systems/assets/40835293/22d34def-03b8-4d99-9701-59a3bf9b3b76)


```bash
Node(
    package='tf2_ros',
    executable='static_transform_publisher',
    name='base_link_to_camera_tf',
    arguments = ['pos_x', 'pos_y', 'pos_z',
                 'rot_x', 'rot_y', 'rot_z',
                 'base_link', 'camera']
    )

```

Hope this helps, all the best!

**Comment by wangzizhe** [comment]
Thank you very much! Yes I'm using TurtleBot3 Waffel Pi, I explored this file and after searching through the internet, I haven't figure it out how I can use this file directly. Could you please provide me more details? I would be very thankful!!

**Comment by Tinker-Twins** [comment]
You can use the [`pose` values](https://github.com/Tinker-Twins/Autonomy-Science-And-Systems/blob/main/Capstone%20Project/capstone_project/turtlebot3/turtlebot3_simulations/turtlebot3_gazebo/models/turtlebot3_waffle_pi/model.sdf#L461C1-L461C44) to populate the transform arguments in the launch file like this:

```
Node(
    package='tf2_ros',
    executable='static_transform_publisher',
    name='base_link_to_camera_tf',
    arguments = [0.073, -0.011, 0.084,
                 0.000, 0.000, 0.000,
                 'base_link', 'camera']
    )

```

**Comment by wangzizhe** [comment]
Thank you very much! 

I'm wondering, since you have used a TurtleBot3 Burger for your project, and there is also a `model.sdf` for TurtleBot3 Burger. Why didn't you directly use these values?

`<pose>0.055 0.0 0.102 0 0 0</pose>`

and how you got your values? For example 0.100 and 1.571? I couldn't find 1.571 at all.

```
['0.055', '0.000', '0.100',
 '0.000', '1.571', '0.000',
    'base_link', 'camera']
```

Thank a lot and wish a nice day!

**Comment by Tinker-Twins** [comment]
We mounted a different camera module ourselves on the robot and hence our values are slightly different (which we measured from the physical robot as discussed earlier). You clould go ahead with the default values in case your are using a TurtleBot3 Burger pre-installed with a camera module.

**Comment by wangzizhe** [comment]
Got it, thank you very much!
